- name: Restart Wiki.js
  community.docker.docker_compose_v2:
    project_src: "{{ item.wiki_instance_path }}"
    state: restarted
  loop: "{{ wikis_docker }}"
  loop_control:
    label: "{{ item.name }}"