FROM postgres:15

# Installer Python et psycopg2 (pour Ansible)
RUN apt-get update && \
    apt-get install -y python3 python3-psycopg2 && \
    rm -rf /var/lib/apt/lists/*
# Ajouter un script d'init pour activer pgcrypto lors du premier démarrage
COPY init-pgcrypto.sql /docker-entrypoint-initdb.d/