---
- name: Créer le dossier Wiki.js
  become: true
  file:
    path: /opt/wiki
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Créer le dossier des fichiers .env pour Wiki.js
  become: true
  file:
    path: /opt/wiki/envs
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Supprimer les anciens fichiers .env
  file:
    path: "/opt/wiki/envs/wiki-{{ item.name }}.env"
    state: absent
  loop: "{{ wikis }}"

- name: Créer le dossier des certificats RDS
  become: true
  file:
    path: /opt/wiki/certs
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Télécharger le certificat SSL RDS global
  become: true
  get_url:
    url: https://truststore.pki.rds.amazonaws.com/global/global-bundle.pem
    dest: /opt/wiki/certs/rds-ca-bundle.pem
    mode: '0644'


- name: Copier le docker-compose.yml de Wiki.js
  become: true
  copy:
    src: docker-compose.yml        # ton fichier compose (dans roles/wiki/files/)
    dest: /opt/wiki/docker-compose.yml
    mode: '0644'
  notify: Restart Wiki.js

  # -------------------------------------------------------------------
# Étape 1 : Lire le fichier clients.json sur la VM
# -------------------------------------------------------------------
- name: Lire clients.json sur la VM
  slurp:
    src: /opt/keycloak/clients.json  # chemin du fichier côté machine distante (VM)
  register: kc_clients_raw    # on stocke le contenu brut (encodé en base64) dans cette variable

# -------------------------------------------------------------------
# Étape 2 : Transformer le contenu en variable JSON utilisable
# -------------------------------------------------------------------
- name: Convertir clients.json en dictionnaire
  set_fact:
    # kc_clients_raw.content = contenu du fichier en base64
    # b64decode = décoder le base64
    # from_json = parser le texte JSON en dictionnaire Python/Ansible
    kc_clients: "{{ kc_clients_raw.content | b64decode | from_json }}"
    # Résultat final : kc_clients = dictionnaire utilisable dans les templates
    # Exemple :
    # kc_clients['ia']     -> secret du client wiki-ia
    # kc_clients['devops'] -> secret du client wiki-devops
    # kc_clients['cyber']  -> secret du client wiki-cyber

- name: Générer les fichiers .env pour chaque instance Wiki.js
  become: true
  template:
    src: env.j2                    # ton template (dans roles/wiki/templates/)
    dest: "/opt/wiki/envs/wiki-{{ item.name }}.env"
    mode: '0644'
  loop: "{{ wikis }}"              # défini dans group_vars/all.yml
  notify: Restart Wiki.js

- name: Copier le Dockerfile Postgres custom
  copy:
    src: Dockerfile.postgres     # placé dans roles/wiki-essaie/files/
    dest: /opt/wiki/Dockerfile.postgres
    mode: '0644'

- name: Construire l’image Postgres custom avec Python
  community.docker.docker_image:
    name: postgres-python
    tag: "15"
    build:
      path: /opt/wiki     # ou le chemin où tu as mis ton Dockerfile.postgres
      dockerfile: Dockerfile.postgres
    source: build
    state: present

- name: Déployer Wiki.js avec Docker Compose v2
  become: true
  community.docker.docker_compose_v2:
    project_src: /opt/wiki
    state: present
  notify: Restart Wiki.js
# -------------------------------------------------------------------
# Étape 3 : Configurer les bases de données dans les conteneurs Docker 
# ------------------------------------------------------------------- 
- name: Attendre que les DB Docker soient prêtes
  command: docker exec {{ item.pg_host }} pg_isready -U {{ item.pg_user }} -d {{ item.pg_db }}
  register: pg_ready
  retries: 10
  delay: 6
  until: pg_ready.rc == 0
  loop: "{{ wikis_docker }}"
  loop_control:
    label: "{{ item.name }}"

  # Installer l’extension pgcrypto (nécessaire pour certaines fonctions de sécurité dans Wiki.js)  

- name: Activer pgcrypto si non présent (sécurité)
  command: >
    docker exec -i {{ item.pg_host }}
    psql -U {{ item.pg_user }} -d {{ item.pg_db }}
    -c "CREATE EXTENSION IF NOT EXISTS pgcrypto;"
  loop: "{{ wikis_docker }}"
  loop_control:
    label: "{{ item.name }}"
  when: item.pg_host is defined

     # Configurer Keycloak comme méthode d’authentification (sso)dans Wiki.js
- name: Configurer Keycloak dans la table authentication (DB Docker)
  command: >
    docker exec -i {{ item.pg_host }}
    psql -U {{ item.pg_user }} -d {{ item.pg_db }} -c
    "INSERT INTO authentication
     (\"key\", \"strategyKey\", \"displayName\", \"isEnabled\", \"order\",
      \"config\", \"selfRegistration\", \"domainWhitelist\", \"autoEnrollGroups\")
     VALUES (
       gen_random_uuid(),
       'keycloak',
       'Keycloak',
       true,
       1,
       jsonb_build_object(
         'host', 'https://sso.{{ base_domain }}',
         'realm', 'saas',
         'clientId', '{{ item.name }}',
         'clientSecret', '{{ kc_clients[item.name] }}',
         'authorizationURL', 'https://sso.{{ base_domain }}/realms/saas/protocol/openid-connect/auth',
         'tokenURL',        'https://sso.{{ base_domain }}/realms/saas/protocol/openid-connect/token',
         'userInfoURL',     'https://sso.{{ base_domain }}/realms/saas/protocol/openid-connect/userinfo',
         'logoutURL',       'https://sso.{{ base_domain }}/realms/saas/protocol/openid-connect/logout',
         'logoutUpstream', false,
         'logoutUpstreamRedirectLegacy', false
       ),
       false,
       '[]'::json,
       '[]'::json
     )
     ON CONFLICT DO NOTHING;"
  loop: "{{ wikis_docker }}"
  loop_control:
    label: "{{ item.name }}"

- name: Installer pip3 (Ubuntu)
  become: true
  apt:
    name: python3-pip
    state: present
    update_cache: yes

  # Installer la librairie Python passlib avec le module bcrypt :
  # - nécessaire pour que le filtre Ansible `password_hash("bcrypt")` fonctionne
  # - utilisé pour générer et insérer des mots de passe hashés dans Wiki.js
- name: Installer passlib via apt (Ubuntu)
  become: true
  apt:
    name: python3-passlib
    state: present
    update_cache: yes


        # Créer un compte admin local dans chaque DB Docker (sera utilisé pour la 1ère connexion)
- name: Créer un compte admin local dans chaque DB Docker
  command: >
    docker exec -i {{ item.pg_host }}
    psql -U {{ item.pg_user }} -d {{ item.pg_db }} -c
    "INSERT INTO \"users\" (
       \"key\", \"email\", \"name\", \"password\",
       \"isSystem\", \"isActive\", \"isVerified\",
       \"providerKey\", \"createdAt\", \"updatedAt\"
     )
     VALUES (
       gen_random_uuid(),
       '{{ item.admin_email }}',
       'Administrator',
       '{{ item.admin_password | password_hash("bcrypt") }}',
       false, true, true,
       'local',
       NOW(), NOW()
     )
     ON CONFLICT (email) DO NOTHING;"
  loop: "{{ wikis_docker }}"
  loop_control:
    label: "{{ item.name }}"
