---
- name: Créer le dossier du provisioner sur la VM
  file:
    path: /opt/provisioner
    state: directory
    mode: '0755'

- name: Installer Ansible Core sur la VM
  apt:
      name: ansible-core
      state: present
      update_cache: yes


- name: Déployer les fichiers applicatifs (Dockerfile, package.json,provisioner.js)
  copy:
    src: "{{ item.src }}"
    dest: "/opt/provisioner/{{ item.dest }}"
    mode: "0644"
  with_items:
    - { src: "Dockerfile",            dest: "Dockerfile" }
    - { src: "package.json",          dest: "package.json" }
    - { src: "provisioner.js",      dest: "provisioner.js" }

- name: Copier le playbook site_wiki.yml
  copy:
    src: "{{ playbook_dir }}/../ansible/site_wiki.yml"
    dest: /opt/site_wiki.yml
    owner: root
    group: ubuntu
    mode: '0640'

- name: Créer le fichier .env sur la VM
  template:
    src: env.j2
    dest: /opt/provisioner/.env
    owner: root
    group: ubuntu 
    mode: '0640'

- name: Créer le fichier .env sur la VM
  template:
    src: env.j2
    dest: /opt/provisioner/.env
    owner: root
    group: ubuntu
    mode: '0640'

- name: Lancer provisionner avec Docker Compose v2
  become: true
  community.docker.docker_compose_v2:
    project_src: /opt/provisioner
    state: present

    
- name: Installer Node.js et npm
  apt:
    name: ['nodejs', 'npm']
    state: present
    update_cache: yes

- name: Installer PM2 globalement
  npm:
    name: pm2
    global: yes
    state: present

#  Étape importante : installation des dépendances du projet
- name: Installer les dépendances Node.js du provisioner
  command: npm install
  args:
    chdir: /opt/provisioner/


