---
- name: Créer le dossier du provisioner sur la VM
  file:
    path: /opt/provisioner
    state: directory
    mode: '0755'

- name: Installer Ansible Core sur la VM
  apt:
      name: ansible-core
      state: present
      update_cache: yes

- name: Copier le code du provisioner
  copy:
    src: "{{ playbook_dir }}/../provisioner/"
    dest: /opt/provisioner/
    owner: root
    group: root
    mode: '0755'

# Ajouter cette tâche avant la copie du site_wiki.yml
- name: Créer le dossier Ansible sur la VM
  file:
    path: /opt/wikisaas-platform/ansible
    state: directory
    owner: root
    group: ubuntu
    mode: '0755'
  
- name: Copier le playbook site_wiki.yml
  copy:
    src: "{{ playbook_dir }}/../ansible/site_wiki.yml"
    dest: /opt/wikisaas-platform/ansible/site_wiki.yml
    owner: root
    group: ubuntu
    mode: '0640'

- name: Créer le fichier .env sur la VM
  template:
    src: env.j2
    dest: /opt/provisioner/.env
    owner: root
    group: ubuntu 
    mode: '0640'

- name: Copier le docker-compose du provisioner sur la VM
  copy:
    src: files/docker-compose.yml
    dest: /opt/provisioner/docker-compose.yml
    owner: root
    group: ubuntu
    mode: '0644'

- name: Lancer le conteneur du provisioner
  command: docker compose up -d
  args:
    chdir: /opt/provisioner/

