---
############################################
# Domaine / ACME
############################################
# Domaine / ACME
############################################
base_domain: "wikiplatform.app"
acme_email: "chamer6@hotmail.com"

############################################
# Outputs Terraform (scalaires)
############################################
ec2_public_ip:  "{{ ec2_public_ip | default(lookup('env','EC2_PUBLIC_IP'), true) }}"
ec2_public_dns: "{{ ec2_public_dns | default(lookup('env','EC2_PUBLIC_DNS'), true) }}"
vpc_id: "{{ vpc_id | default(lookup('env','VPC_ID'), true) }}"
public_subnet_id: "{{ public_subnet_id | default(lookup('env','PUBLIC_SUBNET_ID'), true) }}"
rds_subnet_group: "{{ rds_subnet_group | default(lookup('env','RDS_SUBNET_GROUP'), true) }}"
ec2_security_group_id: "{{ ec2_security_group_id | default(lookup('env','EC2_SECURITY_GROUP_ID'), true) }}"
rds_security_group_id: "{{ rds_security_group_id | default(lookup('env','RDS_SECURITY_GROUP_ID'), true) | default('') }}"
r2_bucket_name: "{{ r2_bucket_name | default(lookup('env','R2_BUCKET_NAME'), true) | default('') }}"
r2_account_id: "{{ r2_account_id | default(lookup('env','R2_ACCOUNT_ID'), true) | default('') }}"
r2_location: "{{ r2_location | default(lookup('env','R2_LOCATION'), true) | default('') }}"
r2_bucket_endpoint: "{{ r2_bucket_endpoint | default(lookup('env','R2_BUCKET_ENDPOINT'), true) | default('') }}"
ec2_user: "ubuntu"
db_host_ia:     "{{ db_host_ia     | default(lookup('env','DB_HOST_IA'), true)     | default('') }}"
db_host_devops: "{{ db_host_devops | default(lookup('env','DB_HOST_DEVOPS'), true) | default('') }}"
db_host_cyber:  "{{ db_host_cyber  | default(lookup('env','DB_HOST_CYBER'), true)  | default('') }}"
############################################
# Wiki.js instances (boucle avec "item") postresql
############################################
wikis:
  - name: ia
    pg_host: "{{ db_host_ia }}"
    pg_user: "wikijs"
    pg_pass: "{{ lookup('env','BDD_PASSWORD') | mandatory }}"
    pg_db: "wiki_ia"
    admin_email: "chamer6@hotmail.com"
    admin_password: "{{ lookup('env','ADMIN_PASS_IA') | mandatory }}"

  - name: devops
    pg_host: "{{ db_host_devops }}"
    pg_user: "wikijs"
    pg_pass: "{{ lookup('env','BDD_PASSWORD') | mandatory }}"
    pg_db: "wiki_devops"
    admin_email: "chamer6@hotmail.com"
    admin_password: "{{ lookup('env','ADMIN_PASS_DEVOPS') | mandatory }}"

  - name: cyber
    pg_host: "{{ db_host_cyber }}"  
    pg_user: "wikijs"
    pg_pass: "{{ lookup('env','BDD_PASSWORD') | mandatory }}"
    pg_db: "wiki_cyber"
    admin_email: "chamer6@hotmail.com"
    admin_password: "{{ lookup('env','ADMIN_PASS_CYBER') | mandatory }}"

############################################
# db docker (utilisé pour déployer des bdd postgres en local avec docker-compose)
############################################

wikis_docker:
  - name: ia
    pg_db: wiki_ia
    pg_user: wikijs
    pg_pass: wikijs_pass
    pg_host: name_db_ia
    admin_email: "admin@ia.wikiplatform.app"
    admin_password: "$2b$12$6ybb0RmnCJ/gxHpsP/gpR.W.2goZHyo8uC8Za7OnyDinevD2xqQnu"

  - name: devops
    pg_db: wiki_devops
    pg_user: wikijs
    pg_pass: wikijs_pass
    pg_host: name_db_devops
    admin_email: "admin@devops.wikiplatform.app"
    admin_password: "$2b$12$HKFt55ikyQKwwcYCngghCeoiP5vDnk.iUdlXqaseVq/cKrlLmDx1e"

  - name: cyber
    pg_db: wiki_cyber
    pg_user: wikijs
    pg_pass: wikijs_pass
    pg_host: name_db_cyber
    admin_email: "admin@cyber.wikiplatform.app"
    admin_password: "$2b$12$jw0jOvrYOHkqBBdEm/0DMOVktwXKR3OJVcm4oBhGoDkDNO3Hvro12"
    
############################################
# Cloudflare R2
############################################
s3_bucket: "{{ r2_bucket_name }}"
s3_endpoint: "{{ r2_bucket_endpoint }}"
s3_access_key: "{{ lookup('env','R2_ACCESS_KEY') | mandatory }}"
s3_secret_key: "{{ lookup('env','R2_SECRET_KEY') | mandatory }}"
cloudflare_api_token_r2: >-
  {{ lookup('env', 'CLOUDFLARE_API_TOKEN_R2')
     | mandatory }}
############################################
# Cloudflare API (pour Traefik DNS-01)
############################################
cloudflare_dns_api_token: >-
  {{ lookup('env','CLOUDFLARE_API_TOKEN') | mandatory }}
############################################
# SSH / Connexion
############################################
ec2_user_ssh_keys: []
############################################
# Dérivés
############################################
wiki_media_base_url: >-
  https://{{ r2_bucket_name }}.{{ r2_account_id
  }}.r2.cloudflarestorage.com
traefik_dashboard_host: "traefik.{{ base_domain }}"
############################################
# Keycloak Admin Password
############################################
kc_admin: admin
kc_admin_password: "{{ lookup('env','KEYCLOAK_ADMIN_PASS') | mandatory }}"
kc_realm: "saas"
postgres_user: "keycloak_wiki"
postgres_password: "{{ lookup('env','KEYCLOAK_DB_PASSWORD') | mandatory }}"
postgres_db: "keycloak_db"
############################################
# postgres bdd rds
############################################
postgres_admin_user: "postgres"
postgres_admin_password: "{{ lookup('env','DB_PASSWORD') | mandatory }}"
postgres_admin_db: "postgres"
