---
- name: Créer le dossier n8n
  become: true
  file:
    path: /opt/n8n
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Créer le dossier data de n8n avec les bons droits
  become: true
  file:
    path: /opt/n8n/data
    state: directory
    owner: 1000   # utilisateur node dans le conteneur
    group: 1000
    mode: '0755'

- name: Copier le docker-compose.yml de n8n
  become: true
  copy:
    src: docker-compose.yml     # va chercher dans roles/n8n/files/
    dest: /opt/n8n/docker-compose.yml
    owner: root
    group: root
    mode: '0644'
  notify: Redémarrer n8n

- name: Démarrer n8n avec Docker Compose v2
  become: true
  community.docker.docker_compose_v2:
    project_src: /opt/n8n
    state: present
