---
# Docker Compose file for multiple Wiki.js instances
# Each instance has its own .env file in ./envs/
# and its own Docker network for database isolation.
# Traefik is used as a reverse proxy with automatic HTTPS via Let's Encrypt.
networks:
  proxy:
    external: true
  wikinet-ia:
    driver: bridge
  wikinet-devops:
    driver: bridge
  wikinet-cyber:
    driver: bridge

services:
  # === Wiki IA ===
  wiki-ia:
    image: ghcr.io/requarks/wiki:2
    container_name: wiki-ia
    restart: unless-stopped
    env_file:
      - ./envs/wiki-ia.env
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.wiki-ia.rule=Host(`ia.wikiplatform.app`)"
      - "traefik.http.routers.wiki-ia.entrypoints=websecure"
      - "traefik.http.routers.wiki-ia.tls.certresolver=myresolver"
    volumes:
      - ./logs/wiki-ia:/logs # Pour les logs  de Wiki.js
        
    networks:
      - proxy
      - wikinet-ia

  # === Wiki DevOps ===
  wiki-devops:
    image: ghcr.io/requarks/wiki:2
    container_name: wiki-devops
    restart: unless-stopped
    env_file:
      - ./envs/wiki-devops.env
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.wiki-devops.rule=Host(`devops.wikiplatform.app`)"
      - "traefik.http.routers.wiki-devops.entrypoints=websecure"
      - "traefik.http.routers.wiki-devops.tls.certresolver=myresolver"
    volumes:
      - ./logs/wiki-devops:/logs # Pour les logs  de Wiki.js
    networks:
      - proxy
      - wikinet-devops

  # === Wiki Cyber ===
  wiki-cyber:
    image: ghcr.io/requarks/wiki:2
    container_name: wiki-cyber
    restart: unless-stopped
    env_file:
      - ./envs/wiki-cyber.env
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.wiki-cyber.rule=Host(`cyber.wikiplatform.app`)"
      - "traefik.http.routers.wiki-cyber.entrypoints=websecure"
      - "traefik.http.routers.wiki-cyber.tls.certresolver=myresolver"
    volumes:
      - ./logs/wiki-cyber:/logs # Pour les logs  de Wiki.js
    networks:
      - proxy
      - wikinet-cyber
