---
# === Installer dépendances pour Docker ===
- name: Install required packages
  become: true
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
      - gnupg
    state: present
    update_cache: true

# === Ajouter clé GPG officielle de Docker ===
- name: Add Docker GPG apt key
  become: true
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

# === Ajouter dépôt Docker officiel ===
- name: Add Docker repository
  become: true
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: present
    filename: docker

# === Installer Docker Engine + CLI + Compose plugin ===
- name: Install Docker Engine and Compose plugin
  become: true
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose-plugin
    state: present
    update_cache: true

# === S'assurer que le service Docker tourne ===
- name: Ensure Docker service is running
  become: true
  ansible.builtin.service:
    name: docker
    state: started
    enabled: true

# === Ajouter l’utilisateur au groupe docker ===
- name: Add user to docker group ({{ ec2_user }})
  become: true
  ansible.builtin.user:
    name: "{{ ec2_user }}"
    groups: docker
    append: true

# === Vérifier versions (debug facultatif) ===
- name: Check Docker version
  become: true
  ansible.builtin.command: docker --version
  register: docker_version
  changed_when: false

- name: Check Docker Compose version
  become: true
  ansible.builtin.command: docker compose version
  register: compose_version
  changed_when: false

- name: Debug Docker versions
  ansible.builtin.debug:
    msg:
      - "Docker: {{ docker_version.stdout }}"
      - "Compose: {{ compose_version.stdout }}"
