---
- name: Déploiement complet plateforme Wiki.js SaaS
  hosts: wikijs_servers
  become: true

  vars_files:
    - group_vars/all.yml

  roles:
    - role: common     # installe Docker + dépendances
    - role: docker     # installe Docker + dépendances
    - role: traefik    # déploie Traefik
    - role: keycloak   # déploie Keycloak + init
    - role: postgres   # prépare les bases PostgreSQL RDS pour Wiki.js  
    - role: wiki       # déploie Wiki.js + init
