---
- name: Déploiement complet plateforme Wiki.js SaaS
  hosts: wikijs_servers
  become: true

  vars_files:
    - group_vars/all.yml

  ---
- name: Deploiement complet plateforme Wiki.js SaaS
  hosts: wikijs_servers
  become: true

  vars_files:
    - group_vars/all.yml

---
- name: Deploiement complet plateforme Wiki.js SaaS
  hosts: wikijs_servers
  become: true

  vars_files:
    - group_vars/all.yml

  pre_tasks:
    - name: Inspecter - Afficher les scalaires principaux
    # ansible-playbook ... --tags inspect
      tags: [inspect]
      debug:
        msg:
          - "ec2_public_ip         = {{ ec2_public_ip }}"
          - "ec2_public_dns        = {{ ec2_public_dns }}"
          - "vpc_id                = {{ vpc_id }}"
          - "public_subnet_id      = {{ public_subnet_id }}"
          - "rds_subnet_group      = {{ rds_subnet_group }}"
          - "ec2_security_group_id = {{ ec2_security_group_id }}"
          - "rds_security_group_id = {{ rds_security_group_id }}"
          - "r2_bucket_name        = {{ r2_bucket_name }}"
          - "r2_account_id         = {{ r2_account_id }}"
          - "r2_location           = {{ r2_location }}"
          - "r2_bucket_endpoint    = {{ r2_bucket_endpoint }}"

    - name: Inspecter - Type des objets recus
      tags: [inspect]
      debug:
        msg:
          - "type(db_endpoints) = {{ db_endpoints | type_debug }}"
          - "type(dns_records)  = {{ dns_records  | type_debug }}"

    - name: Normaliser db_endpoints et dns_records
      set_fact:
        db_eps: >-
          {{ db_endpoints if db_endpoints is mapping
             else (db_endpoints | default('{}') | from_json) }}
        dns_recs: >-
          {{ dns_records if dns_records is mapping
             else (dns_records  | default('{}') | from_json) }}

    - name: Inspecter - db_endpoints formate
      tags: [inspect]
      debug:
        msg: "{{ db_eps | to_nice_json }}"

    - name: Inspecter - dns_records formate
      tags: [inspect]
      debug:
        msg: "{{ dns_recs | to_nice_json }}"

    - name: Inspecter - Acces (db host 'cyber' et premier DNS)
      tags: [inspect]
      debug:
        msg:
          - "db host (cyber) = {{ db_eps.cyber | default('non defini') }}"
          - "first_dns_name = {{ first_dns_name }}"
          - "first_dns value = {{ dns_recs[first_dns_name] | default('') }}"

    - name: Initialiser wikis_final
      set_fact:
        wikis_final: []

    - name: Construire wikis_final avec pg_host depuis db_eps
      set_fact:
        wikis_final: "{{ wikis_final + [ wiki | combine({'pg_host': (db_eps[wiki.name] | default(wiki.pg_host | default('')))}) ] }}"
      loop: "{{ wikis }}"
      loop_control:
        loop_var: wiki

    - name: Inspecter - Apercu wikis_final
      tags: [inspect]
      debug:
        var: wikis_final

  roles:
    - role: common
    - role: docker
    - role: traefik
    - role: keycloak
    - role: postgres
    - role: wiki
      vars:
        wikis: "{{ wikis_final | default(wikis) }}"
