---
- name: Deploiement complet plateforme Wikijs SaaS
  hosts: wikijs_servers
  become: true

  vars_files:
    - group_vars/all.yml

  roles:
    - role: common
    - role: docker
    - role: traefik
    - role: keycloak
    - role: postgres
    - role: wiki
      
