---
- name: Déploiement complet plateforme Wikijs SaaS
  hosts: wikijs_servers
  become: true

  # 🔹 On charge les variables globales et les instances fixes
  vars_files:
    - group_vars/all.yml   # Contient wikis_docker (ia/devops/cyber) + base_domain + kc_clients

  # 🔹 Étape 1 : Installation et configuration de la plateforme commune
  roles:
    - role: common       # Mise à jour système, firewall, utilisateurs
    - role: docker       # Installation de Docker + Compose
    - role: traefik      # Reverse proxy + certificats Let's Encrypt
    - role: postgres     # Création des bases RDS + utilisateurs
    - role: keycloak     # Authentification SSO
    - role: wiki-essaie  # Rôle de gestion des instances Wiki.js
