---
- name: Déploiement complet plateforme Wiki.js SaaS
  hosts: wikijs_servers
  become: true

  vars_files:
    - group_vars/all.yml

  roles:
    - role: common     # installe Docker + dépendances
    - role: Docker   # installe Docker Compose  
