---
version: "3.9"

services:
  traefik:
    image: traefik:v3.0
    container_name: traefik
    restart: always
    command:
      # Découverte Docker
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"

      # Entrypoints HTTP + HTTPS avec redirection automatique
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
      - "--entrypoints.websecure.address=:443"

      # ACME Let's Encrypt via DNS challenge (wildcard)
      - "--certificatesresolvers.le.acme.dnschallenge=true"
      - "--certificatesresolvers.le.acme.dnschallenge.provider=cloudflare"
      - "--certificatesresolvers.le.acme.email=${ACME_EMAIL}"
      - "--certificatesresolvers.le.acme.storage=/letsencrypt/acme.json"

      # Headers de sécurité
      - "--middlewares.secureHeaders.headers.stsSeconds=31536000"
      - "--middlewares.secureHeaders.headers.stsIncludeSubdomains=true"
      - "--middlewares.secureHeaders.headers.frameDeny=true"
      - "--middlewares.secureHeaders.headers.contentTypeNosniff=true"

    ports:
      - "80:80"
      - "443:443"

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./letsencrypt:/letsencrypt

    env_file:
      - .env

    labels:
      # Dashboard Traefik (protégé par auth basique)
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.rule=Host(`traefik.${DOMAIN}`)"
      - "traefik.http.routers.traefik.entrypoints=websecure"
      - "traefik.http.routers.traefik.tls=true"
      - "traefik.http.services.traefik.loadbalancer.server.port=8080"

      # Middleware Auth basique (login admin / mot de passe hashé)
      - "traefik.http.middlewares.traefik-auth.basicauth.users=admin:$apr1$/pBuvzke$LUWOGmAGGAArsVoX3Znyr1"

      # Application des middlewares : Auth + Headers de sécurité
      - "traefik.http.routers.traefik.middlewares=traefik-auth,secureHeaders@docker"
  networks:
  proxy:
    name: proxy
    external: false
