name: Ansible Deploy

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:   # ici je transforme les secrets GitHub en variables d'environnement
      ADMIN_PASS_CYBER: ${{ secrets.ADMIN_PASS_CYBER }}
      ADMIN_PASS_DEVOPS: ${{ secrets.ADMIN_PASS_DEVOPS }}
      ADMIN_PASS_IA: ${{ secrets.ADMIN_PASS_IA }}
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      CLOUDFLARE_API_TOKEN_R2: ${{ secrets.CLOUDFLARE_API_TOKEN_R2 }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      KEYCLOAK_ADMIN_PASS: ${{ secrets.KEYCLOAK_ADMIN_PASS }}
      R2_ACCESS_KEY: ${{ secrets.R2_ACCESS_KEY }}
      R2_SECRET_KEY: ${{ secrets.R2_SECRET_KEY }}
      TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}
      KEYCLOAK_DB_PASSWORD: ${{ secrets.KEYCLOAK_DB_PASSWORD }} # mot de passe de la BDD Postgres de Keycloak
      VM_SSH_KEY: ${{ secrets.VM_SSH_KEY }}  # clé privée SSH pour se connecter à la VM

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # 1) Recréer la clé SSH à partir du secret GitHub
      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          printf "%s" "$VM_SSH_KEY" > ~/.ssh/newtest.pem
          chmod 600 ~/.ssh/newtest.pem

      # 2) Installer Ansible
      - name: Install Ansible
        run: sudo apt-get update && sudo apt-get install -y ansible

      # 2bis) Installer les collections nécessaires (dont ansible.posix)
      - name: Install Ansible collections
        run: ansible-galaxy collection install ansible.posix
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.5   # ou la version que tu utilises

      - name: Export Terraform outputs
        run: |
          set -euo pipefail
          O=$(terraform -chdir=./terraform output -json)

          echo "EC2_PUBLIC_IP=$(echo "$O" | jq -r .ec2_public_ip.value)" >> $GITHUB_ENV
          echo "EC2_PUBLIC_DNS=$(echo "$O" | jq -r .ec2_public_dns.value)" >> $GITHUB_ENV
          echo "DB_ENDPOINTS=$(echo "$O" | jq -c .db_endpoints.value)" >> $GITHUB_ENV
          echo "DNS_RECORDS=$(echo "$O" | jq -c .dns_records.value)" >> $GITHUB_ENV
          echo "R2_BUCKET_NAME=$(echo "$O" | jq -r .r2_bucket_name.value)" >> $GITHUB_ENV
          echo "R2_ACCOUNT_ID=$(echo "$O" | jq -r .r2_account_id.value)" >> $GITHUB_ENV
          echo "R2_LOCATION=$(echo "$O" | jq -r .r2_location.value)" >> $GITHUB_ENV
          echo "R2_BUCKET_ENDPOINT=$(echo "$O" | jq -r .r2_bucket_endpoint.value)" >> $GITHUB_ENV
          echo "VPC_ID=$(echo "$O" | jq -r .vpc_id.value)" >> $GITHUB_ENV
          echo "PUBLIC_SUBNET_ID=$(echo "$O" | jq -r .public_subnet_id.value)" >> $GITHUB_ENV
          echo "RDS_SUBNET_GROUP=$(echo "$O" | jq -r .rds_subnet_group.value)" >> $GITHUB_ENV
          echo "EC2_SECURITY_GROUP_ID=$(echo "$O" | jq -r .ec2_security_group_id.value)" >> $GITHUB_ENV
          echo "RDS_SECURITY_GROUP_ID=$(echo "$O" | jq -r .rds_security_group_id.value)" >> $GITHUB_ENV


      # 3) Ajouter le host dans known_hosts (évite le "Host key verification failed")
      - name: Add SSH known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H wikiplatform.app >> ~/.ssh/known_hosts

      # 4) Exécuter Ansible
      - name: Run Ansible Playbook
        run: ansible-playbook -i ansible/inventories/prod/hosts.ini ansible/site.yml
